version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: alki-ng01
    ports:
      - "8000:8000"
    volumes:
      - ./src/static:/static
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: alki-web01
    #command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn alkilab.wsgi -b 0.0.0.0:8080"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8080"

    depends_on:
      - db
    volumes:
      - ./src:/src
    expose:
      - "8080"

  db:
    image: postgres:latest
    container_name: alki-db01
